[build-system]
requires = [
    "scikit-build-core>=0.10",
    "pybind11>=2.12"
]
build-backend = "scikit_build_core.build"

[project]
name = "ccd"
version = "0.0.1"
description = "High-performance C++/Python implementation of Continuous Change Detection algorithm for Landsat."
readme = "README.md"
requires-python = ">=3.12"

[tool.scikit-build]
wheel.packages = ["python/ccd"]
cmake.args = [
    "-G",
    "Visual Studio 17 2022"
]