[build-system]
requires = [
    "scikit-build-core>=0.10",
    "pybind11>=2.12"
]
build-backend = "scikit_build_core.build"

[project]
name = "ccdcpp"
version = "0.1.0"
description = "High-performance C++/Python implementation of Continuous Change Detection algorithm for Landsat."
readme = "README.md"
requires-python = ">=3.12"

[tool.scikit-build]
cmake.args = [
    "-DCCD_BUILD_PYTHON=ON",
    "-DCCD_BUILD_TESTS=OFF",
    "-DCCD_INSTALL_CPP=OFF",
    "-DCMAKE_BUILD_TYPE=Release"
]
[tool.scikit-build.wheel]
packages = ["python/ccdcpp"]